---
name: build
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'windows-2019', 'macos-10.15']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - uses: actions/checkout@v2
      - name: build without cgo
        run: make
        env:
          CGO_ENABLED: 0
      - name: install cgo dependencies (Linux)
        run: sudo apt-get install libpcap-dev
        if: ${{ matrix.os == 'ubuntu-20.04' }}
      - name: build with cgo
        run: make
        env:
          CGO_ENABLED: 1
